on: push
name: go tests
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: run
        uses: cedrickring/golang-action@1.6.0
        env:
          PROJECT_PATH: "."
